name: Publish Snapshot package

on:
  push:
    branches: [main]

jobs:
  publish-snapshot:
    uses: calypsonet/calypsonet-actions/.github/workflows/reusable-publish-snapshot.yml@main # NOSONAR - Same organization, trusted source
    secrets: inherit # NOSONAR - Same organization, trusted source
